name: build

on:
  push:
    branches:
      - 'master'
    paths:
      - '**.go'

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        
      - name: build
        run: |
          go version
          go build .
          


