name: build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        
      - name: build
        run: go build -o dnstapparse . 


