name: do release

on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build
      run: |
        GOOS=linux GOARCH=arm64 go build -o dnstapparse-linux-arm64 .
        GOOS=linux GOARCH=amd64 go build -o dnstapparse-linux-amd64 .
        GOOS=windows GOARCH=amd64 go build -o dnstapparse-windows-amd64.exe .

    - name: github-action-publish-binaries
      uses: skx/github-action-publish-binaries@release-0.15
     
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'dnstapparse*'
